output "waf_rate_based_rule" {
  value = module.waf.waf_rate_based_rule
}

output "waf_acl_id" {
  description = "WAF ACL ID generated by the module"
  value       = module.waf.waf_acl_id
}

output "id" {
  value = module.waf.id
}

output "ipset_bad-bot-v4_arn" {
  value = module.waf.ipset_bad-bot-v4_arn
}
output "ipset_bad-bot-v6_arn" {
  value = module.waf.ipset_bad-bot-v6_arn
}

output "ipset_bad-bot-v4_id" {
  value = module.waf.ipset_bad-bot-v4_id
}
output "ipset_bad-bot-v6_id" {
  value = module.waf.ipset_bad-bot-v6_id
}

output "waf_rate_based_rule" {
  value = module.waf.waf_rate_based_rule
}

output "waf_sqs_dead_letter_arn" {
  value = module.waf.waf_sqs_dead_letter_arn
}

output "waf_sqs_arn" {
  value = module.waf.waf_sqs_arn
}